-- Create database
CREATE DATABASE CloudNATO;
GO

-- Use the new database
USE CloudNATO;
GO

-- Create Users table
CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL
);
GO

-- Insert some fake users
INSERT INTO Users (Username, Password) VALUES
('skybyte321@gmail.com', 'CrimsonWolf99!'),
('echohunter5@outlook.com', 'PixelStorm22$'),
('nova.blast01@onemedia.com', 'Frostbite33!'),
('quantumfox24@gmail.com', 'ShadowRogue77@'),
('bytebuster007@outlook.com', 'CyberNinja88#'),
('darkwave999@onemedia.com', 'GlitchSpark42!'),
('starfallx9@gmail.com', 'EchoBlade66$'),
('ghostline213@outlook.com', 'ZeroPulse11!'),
('neonfrost88@onemedia.com', 'HyperNova123$'),
('phantomflux72@gmail.com', 'ByteKnight55!'),
('radioriot23@outlook.com', 'SilentCore44$'),
('cyberflarex1@onemedia.com', 'NovaStrike77!'),
('astro.venom19@gmail.com', 'WarpStorm99!'),
('blitzflux303@outlook.com', 'ShadowCore12$'),
('echoquake77@onemedia.com', 'SpectralWolf66!'),
('quantumvibe02@gmail.com', 'FrozenPulse45@'),
('ghostwirex5@outlook.com', 'CyberFrost99!'),
('hyperbyte003@onemedia.com', 'SilentNova88$'),
('darknova24@gmail.com', 'ZeroStorm55!'),
('photonflux007@outlook.com', 'ByteCore11@'),
('skylinewave88@onemedia.com', 'NeonPulse99!'),
('novaecho03@gmail.com', 'SpecterRush33!'),
('quantumshock05@outlook.com', 'WarpPulse44@'),
('glitchvortex9@onemedia.com', 'CrimsonByte22!'),
('cyberline2000@gmail.com', 'GhostFlare88$'),
('pixelstormx8@outlook.com', 'HyperStorm77!'),
('ghostnova900@onemedia.com', 'FrostCore55!'),
('bytequake500@gmail.com', 'NovaRush99!'),
('darkflare12@outlook.com', 'SpectralEcho66@'),
('radiowolf88@onemedia.com', 'QuantumFrost44!'),
('frostbyte404@gmail.com', 'PulseNova22$'),
('phantomwarp12@outlook.com', 'ByteRush33!'),
('novaquake23@onemedia.com', 'NeonStorm88!'),
('cybernova98@gmail.com', 'ZeroRush55$'),
('blitznova77@outlook.com', 'WarpEcho22!'),
('quantumwolf1@onemedia.com', 'FrozenByte99!'),
('ghostbyte88@gmail.com', 'NovaCore66@'),
('darknova03@outlook.com', 'SpectralStorm11$'),
('astroquake15@onemedia.com', 'HyperEcho88!'),
('pixelquake900@gmail.com', 'FrostRush77!'),
('ghostflux72@outlook.com', 'CyberNova44@'),
('quantumflarex1@onemedia.com', 'SilentByte33!'),
('neonstorm03@gmail.com', 'PulseEcho99$'),
('cyberstormx4@outlook.com', 'NovaPulse88!'),
('blitzquake11@onemedia.com', 'CrimsonRush55@'),
('nova.warp21@gmail.com', 'ZeroNova22!'),
('echoquake09@outlook.com', 'HyperByte99$'),
('ghostnova007@onemedia.com', 'PulseStorm77!'),
('bytewavex8@gmail.com', 'FrozenRush66!'),
('cyberbyte900@outlook.com', 'NovaRush33@'),
('darkpulse77@onemedia.com', 'NeonByte22!'),
('radiowarp24@gmail.com', 'HyperNova11$'),
('quantumcorex9@outlook.com', 'SpectralRush88!'),
('glitchnova33@onemedia.com', 'CyberCore55$'),
('phantomcorex1@gmail.com', 'WarpNova44!'),
('novaquakex5@outlook.com', 'PulseRush66$'),
('cyberflare77@onemedia.com', 'FrozenStorm88!'),
('skyhunter02@gmail.com', 'EchoRush33@'),
('ghostwavex1@outlook.com', 'SpectralNova22!'),
('darkwarp03@onemedia.com', 'NovaEcho99$'),
('bytehunter77@gmail.com', 'ZeroRush77!'),
('neonbytex9@outlook.com', 'HyperCore44$'),
('astrocore03@onemedia.com', 'PulseNova33!'),
('ghostpulsex8@gmail.com', 'FrozenRush88!'),
('quantumbyte03@outlook.com', 'SpectralRush22!'),
('blitzstorm88@onemedia.com', 'WarpEcho55$'),
('cyberquake77@gmail.com', 'ZeroNova11!'),
('nova.rushx3@outlook.com', 'HyperPulse99$'),
('ghostnova24@onemedia.com', 'FrozenEcho66!'),
('byteflarex8@gmail.com', 'SpectralRush44!'),
('darkstormx9@outlook.com', 'NeonPulse77$'),
('pixelrush13@onemedia.com', 'CyberNova33!'),
('quantumflux09@gmail.com', 'PulseCore99$'),
('ghostwarp24@outlook.com', 'FrozenRush22!'),
('astroquake300@onemedia.com', 'ZeroPulse55!'),
('skyquakex3@gmail.com', 'HyperRush88$'),
('novaquake13@outlook.com', 'FrozenNova66!'),
('ghostflarex7@onemedia.com', 'PulseEcho33!'),
('bytequake03@gmail.com', 'CrimsonRush99$'),
('cyberbyte44@outlook.com', 'SpectralNova77!'),
('quantumcorex2@onemedia.com', 'ZeroRush11!'),
('darknova33@gmail.com', 'PulseNova55$'),
('pixelwolf24@outlook.com', 'FrozenEcho88!'),
('ghostquakex3@onemedia.com', 'HyperRush66$'),
('quantumwolf77@gmail.com', 'PulseStorm44!'),
('nova.corex9@outlook.com', 'CrimsonRush22!'),
('cyberquake09@onemedia.com', 'FrozenPulse11$'),
('phantomflare03@gmail.com', 'ZeroNova99!'),
('byteflarex7@outlook.com', 'HyperRush33$'),
('ghostnova2000@onemedia.com', 'PulseEcho77!'),
('skybytex8@gmail.com', 'FrozenNova88!'),
('darkrushx9@outlook.com', 'SpectralRush55$'),
('novaquakex7@onemedia.com', 'CyberPulse22!'),
('ghoststorm07@gmail.com', 'PulseNova44$'),
('quantumrush13@outlook.com', 'ZeroRush66!'),
('astroquakex1@onemedia.com', 'FrozenEcho11!'),
('neonbyte03@gmail.com', 'HyperRush77$'),
('cyberquakex7@outlook.com', 'PulseNova88!'),
('ghostquakex5@onemedia.com', 'SpectralRush33!');

GO
