// AppInstallerDialog.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Windows.Forms;
using Newtonsoft.Json; // For more robust serialization/deserialization
using Newtonsoft.Json.Linq; // Added for potential future use or more robust JSON handling

namespace NATO_OS_7
{
    // This class will represent the information for a single control
    public class ControlInfo
    {
        public string Type { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public int Left { get; set; } // Made public
        public int Top { get; set; }  // Made public
        public int Width { get; set; } // Made public
        public int Height { get; set; } // Corrected typo and made public
        public Dictionary<string, string> Properties { get; set; } = new Dictionary<string, string>();
        public Dictionary<string, string> EventHandlers { get; set; } = new Dictionary<string, string>(); // New: Store event handlers
    }

    // This class will represent the entire app package
    public class AppPackage
    {
        public string AppName { get; set; }
        public string AppDescription { get; set; }
        public List<ControlInfo> Controls { get; set; } = new List<ControlInfo>();
        public string AppCode { get; set; } = ""; // New: Store the C# code for the app
    }

    public partial class AppInstallerDialog : Form
    {
        private TextBox txtAppUrl;
        private FlowLayoutPanel flowLayoutPanelApps;
        private Button btnLoadApps;
        private Button btnUploadPackage;
        private Form2 _mainForm; // Reference to the main OS form

        // Fields to store app info for post-dialog processing
        private AppPackage _appPackageToPin;
        private GroupBox _appGroupBoxToPin;

        public AppInstallerDialog(Form2 mainForm)
        {
            InitializeComponent();
            _mainForm = mainForm;
            this.Text = "App Installer";
            this.Size = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;

            // Setup UI for App Installer
            Label lblAppUrl = new Label { Text = "Enter App URL (e.g., ajm19826.github.io/NATO-OS-Pkgs/pkgs/):", AutoSize = true, Location = new Point(10, 10) };
            txtAppUrl = new TextBox { Location = new Point(10, 30), Width = 400, Text = "https://ajm19826.github.io/NATO-OS-Pkgs/pkgs/apps.json" }; // Default URL for testing
            btnLoadApps = new Button { Text = "Load Apps from URL", Location = new Point(420, 28), AutoSize = true };
            btnUploadPackage = new Button { Text = "Upload Package (.npkg)", Location = new Point(550, 28), AutoSize = true };

            flowLayoutPanelApps = new FlowLayoutPanel
            {
                Location = new Point(10, 70),
                Size = new Size(760, 500),
                AutoScroll = true,
                FlowDirection = FlowDirection.TopDown,
                WrapContents = false, // Ensure items stack vertically
                BorderStyle = BorderStyle.FixedSingle
            };

            this.Controls.Add(lblAppUrl);
            this.Controls.Add(txtAppUrl);
            this.Controls.Add(btnLoadApps);
            this.Controls.Add(btnUploadPackage);
            this.Controls.Add(flowLayoutPanelApps);

            btnLoadApps.Click += BtnLoadApps_Click;
            btnUploadPackage.Click += BtnUploadPackage_Click;
        }

        private void InitializeComponent()
        {
            // This is typically generated by the designer, but for a new form, we define it here.
            this.SuspendLayout();
            // AppInstallerDialog
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Name = "AppInstallerDialog";
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private async void BtnLoadApps_Click(object sender, EventArgs e)
        {
            string url = txtAppUrl.Text.Trim();
            if (string.IsNullOrEmpty(url))
            {
                MessageBox.Show("Please enter an App URL.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            try
            {
                using (HttpClient client = new HttpClient())
                {
                    // Ensure the URL ends with a slash if it's a directory, or points directly to a JSON file
                    if (!url.EndsWith("/"))
                    {
                        url += "/"; // Assume it's a directory containing apps.json
                    }
                    string jsonUrl = url + "apps.json"; // Assuming apps metadata is in apps.json

                    string jsonContent = await client.GetStringAsync(jsonUrl);
                    List<AppPackage> availableApps = JsonConvert.DeserializeObject<List<AppPackage>>(jsonContent);

                    DisplayAvailableApps(availableApps);
                }
            }
            catch (HttpRequestException httpEx)
            {
                MessageBox.Show($"Error fetching app list from URL: {httpEx.Message}. Please check the URL and your internet connection.", "Network Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch (Newtonsoft.Json.JsonException jsonEx) // Specify Newtonsoft.Json.JsonException
            {
                MessageBox.Show($"Error parsing app list: {jsonEx.Message}. The JSON format might be incorrect.", "Data Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"An unexpected error occurred: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void DisplayAvailableApps(List<AppPackage> apps)
        {
            flowLayoutPanelApps.Controls.Clear(); // Clear existing apps

            if (apps == null || apps.Count == 0)
            {
                Label noAppsLabel = new Label { Text = "No apps found at this URL.", AutoSize = true, ForeColor = Color.Red };
                flowLayoutPanelApps.Controls.Add(noAppsLabel);
                return;
            }

            foreach (var app in apps)
            {
                GroupBox appGroupBox = CreateAppGroupBox(app);
                flowLayoutPanelApps.Controls.Add(appGroupBox);
            }
        }

        private GroupBox CreateAppGroupBox(AppPackage app)
        {
            GroupBox groupBox = new GroupBox
            {
                Text = app.AppName,
                Size = new Size(740, 100),
                Margin = new Padding(5),
                Tag = app // Store the entire AppPackage object in the Tag for easy retrieval
            };

            Label lblDescription = new Label
            {
                Text = app.AppDescription,
                Location = new Point(10, 20),
                AutoSize = true,
                MaximumSize = new Size(720, 0) // Allow multiline description
            };

            Button btnInstall = new Button
            {
                Text = "Install App",
                Location = new Point(10, 60),
                AutoSize = true
            };
            btnInstall.Click += (sender, e) => InstallApp(app);

            groupBox.Controls.Add(lblDescription);
            groupBox.Controls.Add(btnInstall);

            return groupBox;
        }

        private void InstallApp(AppPackage app)
        {
            try
            {
                // Before loading, perform a basic virus scan on the app code
                if (_mainForm.ScanAppCodeForViruses(app.AppCode))
                {
                    MessageBox.Show("Potential malicious code detected in the app. Installation aborted.", "Security Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    return;
                }

                // Load the app and get a reference to the created GroupBox
                GroupBox installedAppGroupBox = _mainForm.LoadAppFromPackage(app);

                // If the app was successfully loaded, store info for pinning after dialog closes
                if (installedAppGroupBox != null)
                {
                    _appPackageToPin = app;
                    _appGroupBoxToPin = installedAppGroupBox;
                    MessageBox.Show($"App '{app.AppName}' installed and loaded onto the OS!", "Installation Complete", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    this.Close(); // Close the installer after installation
                }
                else
                {
                    MessageBox.Show($"Failed to install app '{app.AppName}'. See console for details.", "Installation Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error installing app: {ex.Message}", "Installation Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void BtnUploadPackage_Click(object sender, EventArgs e)
        {
            using (OpenFileDialog openFileDialog = new OpenFileDialog())
            {
                openFileDialog.Filter = "NATO OS Package Files (*.npkg)|*.npkg|All Files (*.*)|*.*";
                openFileDialog.Title = "Select an App Package (.npkg) to Upload";

                if (openFileDialog.ShowDialog() == DialogResult.OK)
                {
                    try
                    {
                        string filePath = openFileDialog.FileName;
                        string jsonContent = File.ReadAllText(filePath);
                        AppPackage loadedPackage = JsonConvert.DeserializeObject<AppPackage>(jsonContent);

                        if (loadedPackage != null)
                        {
                            // Before loading, perform a basic virus scan on the app code
                            if (_mainForm.ScanAppCodeForViruses(loadedPackage.AppCode))
                            {
                                MessageBox.Show("Potential malicious code detected in the app. Loading aborted.", "Security Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                return;
                            }

                            // Load the app and get a reference to the created GroupBox
                            GroupBox installedAppGroupBox = _mainForm.LoadAppFromPackage(loadedPackage);

                            // If the app was successfully loaded, store info for pinning after dialog closes
                            if (installedAppGroupBox != null)
                            {
                                _appPackageToPin = loadedPackage;
                                _appGroupBoxToPin = installedAppGroupBox;
                                MessageBox.Show($"Package '{loadedPackage.AppName}' loaded successfully!", "Package Loaded", MessageBoxButtons.OK, MessageBoxIcon.Information);
                                this.Close();
                            }
                            else
                            {
                                MessageBox.Show($"Failed to load package '{loadedPackage.AppName}'. See console for details.", "Load Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }
                        }
                        else
                        {
                            MessageBox.Show("Failed to load package. The file might be corrupted or in an invalid format.", "Load Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                    catch (Newtonsoft.Json.JsonException jsonEx) // Specify Newtonsoft.Json.JsonException
                    {
                        MessageBox.Show($"Error parsing package file: {jsonEx.Message}. The file might be corrupted or in an invalid JSON format.", "File Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show($"An error occurred while uploading the package: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
        }

        // Public properties to expose the app info after the dialog closes
        public AppPackage AppPackageToPin => _appPackageToPin;
        public GroupBox AppGroupBoxToPin => _appGroupBoxToPin;
    }
}